apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeReplication
metadata:
  name: dr-app
  namespace: test
spec:
  dataSource:
    apiGroup: ''
    kind: PersistentVolumeClaim
    name: dr-app-data
  replicationState: primary
  volumeReplicationClass: odf-rbd-volumereplicationclass
