kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dr-app-data
  namespace: demo-dr-with-submariner-and-odf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-mirror
  volumeMode: Filesystem
