kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-mirror
  volumeMode: Filesystem
