kind: Service
apiVersion: v1
metadata:
  name: adr-app-service
  namespace: demo-dr-with-submariner-and-odf
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  selector:
    app: dr-app-httpd
