kind: Service
apiVersion: v1
metadata:
  name: adr-app-service
  namespace: test
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  selector:
    app: dr-app-httpd
